# Central half
CONFIG_ZMK_KEYBOARD_NAME="arc"
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# USB HID
CONFIG_ZMK_USB=n
CONFIG_USB_DEVICE_STACK=n
CONFIG_USB_DEVICE_HID=n

# Optional
CONFIG_ZMK_USB_LOGGING=n  # disable for now to avoid dependency issues
