# Central half
CONFIG_ZMK_KEYBOARD_NAME="Arcturis"
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# USB HID
CONFIG_ZMK_USB=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_HID=y

# Optional
CONFIG_ZMK_USB_LOGGING=n  # disable for now to avoid dependency issues
